// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDphdZu_LkOy4jfxMeicyMUiO_q6bsqF_g',
    appId: '1:157034138432:web:b8d35b5431103f1bc188a5',
    messagingSenderId: '157034138432',
    projectId: 'ecommerce-1ff82',
    authDomain: 'ecommerce-1ff82.firebaseapp.com',
    storageBucket: 'ecommerce-1ff82.firebasestorage.app',
    measurementId: 'G-PH1DKJZPB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvyZuM0kr-sW44KpZpymXjY1EZ1BnUxzY',
    appId: '1:157034138432:android:121f6eed7ec04ac6c188a5',
    messagingSenderId: '157034138432',
    projectId: 'ecommerce-1ff82',
    storageBucket: 'ecommerce-1ff82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAZ0e-cG_awAKu7nFClg5ZujA1LbCjgxw',
    appId: '1:157034138432:ios:bb4f8b430141ad91c188a5',
    messagingSenderId: '157034138432',
    projectId: 'ecommerce-1ff82',
    storageBucket: 'ecommerce-1ff82.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAZ0e-cG_awAKu7nFClg5ZujA1LbCjgxw',
    appId: '1:157034138432:ios:bb4f8b430141ad91c188a5',
    messagingSenderId: '157034138432',
    projectId: 'ecommerce-1ff82',
    storageBucket: 'ecommerce-1ff82.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDphdZu_LkOy4jfxMeicyMUiO_q6bsqF_g',
    appId: '1:157034138432:web:74a28cce9e9bfaa7c188a5',
    messagingSenderId: '157034138432',
    projectId: 'ecommerce-1ff82',
    authDomain: 'ecommerce-1ff82.firebaseapp.com',
    storageBucket: 'ecommerce-1ff82.firebasestorage.app',
    measurementId: 'G-C1ZPJEPNNW',
  );
}
